//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClivoxApp {
    using System;
    using System.Reflection;
    

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClivoxApp.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string client_CompanyName {
            get {
                return ResourceManager.GetString("client_CompanyName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Is Company?.
        /// </summary>
        public static string client_IsCompany {
            get {
                return ResourceManager.GetString("client_IsCompany", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string client_FirstName {
            get {
                return ResourceManager.GetString("client_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string client_LastName {
            get {
                return ResourceManager.GetString("client_LastName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string client_Gender {
            get {
                return ResourceManager.GetString("client_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string client_GenderMale {
            get {
                return ResourceManager.GetString("client_GenderMale", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string client_GenderFemale {
            get {
                return ResourceManager.GetString("client_GenderFemale", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string client_Email {
            get {
                return ResourceManager.GetString("client_Email", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string client_PhoneNumber {
            get {
                return ResourceManager.GetString("client_PhoneNumber", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string client_Address {
            get {
                return ResourceManager.GetString("client_Address", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Company or Person.
        /// </summary>
        public static string client_Address_CompanyOrPerson {
            get {
                return ResourceManager.GetString("client_Address_CompanyOrPerson", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string client_Address_Street {
            get {
                return ResourceManager.GetString("client_Address_Street", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string client_Address_PostalCode {
            get {
                return ResourceManager.GetString("client_Address_PostalCode", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string client_Address_City {
            get {
                return ResourceManager.GetString("client_Address_City", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string client_Address_Country {
            get {
                return ResourceManager.GetString("client_Address_Country", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        public static string country_Germany {
            get {
                return ResourceManager.GetString("country_Germany", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Austria.
        /// </summary>
        public static string country_Austria {
            get {
                return ResourceManager.GetString("country_Austria", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        public static string country_Belgium {
            get {
                return ResourceManager.GetString("country_Belgium", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Czech Republic.
        /// </summary>
        public static string country_CzechRepublic {
            get {
                return ResourceManager.GetString("country_CzechRepublic", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        public static string country_Denmark {
            get {
                return ResourceManager.GetString("country_Denmark", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string country_France {
            get {
                return ResourceManager.GetString("country_France", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        public static string country_Luxembourg {
            get {
                return ResourceManager.GetString("country_Luxembourg", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Netherlands.
        /// </summary>
        public static string country_Netherlands {
            get {
                return ResourceManager.GetString("country_Netherlands", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        public static string country_Poland {
            get {
                return ResourceManager.GetString("country_Poland", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        public static string country_Switzerland {
            get {
                return ResourceManager.GetString("country_Switzerland", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        public static string invoice_InvoiceNumber {
            get {
                return ResourceManager.GetString("invoice_InvoiceNumber", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string invoice_InvoiceDate {
            get {
                return ResourceManager.GetString("invoice_InvoiceDate", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string invoice_DueDate {
            get {
                return ResourceManager.GetString("invoice_DueDate", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Service Date.
        /// </summary>
        public static string invoice_ServiceDate {
            get {
                return ResourceManager.GetString("invoice_ServiceDate", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Add invoice.
        /// </summary>
        public static string jobs_AddInvoice {
            get {
                return ResourceManager.GetString("jobs_AddInvoice", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to New Invoice.
        /// </summary>
        public static string jobs_NewInvoice {
            get {
                return ResourceManager.GetString("jobs_NewInvoice", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Edit Invoice.
        /// </summary>
        public static string jobs_EditInvoice {
            get {
                return ResourceManager.GetString("jobs_EditInvoice", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Loading client....
        /// </summary>
        public static string jobs_ClientLoading {
            get {
                return ResourceManager.GetString("jobs_ClientLoading", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Unknown client.
        /// </summary>
        public static string jobs_ClientUnknown {
            get {
                return ResourceManager.GetString("jobs_ClientUnknown", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string jobs_Total {
            get {
                return ResourceManager.GetString("jobs_Total", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string jobs_Items {
            get {
                return ResourceManager.GetString("jobs_Items", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string jobs_ExportToExcel {
            get {
                return ResourceManager.GetString("jobs_ExportToExcel", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Invoice.
        /// </summary>
        public static string editInvoiceDialog_Title {
            get {
                return ResourceManager.GetString("editInvoiceDialog_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Invoice Items.
        /// </summary>
        public static string editInvoiceDialog_InvoiceItems {
            get {
                return ResourceManager.GetString("editInvoiceDialog_InvoiceItems", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Per Hour.
        /// </summary>
        public static string editInvoiceDialog_PerHour {
            get {
                return ResourceManager.GetString("editInvoiceDialog_PerHour", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string editInvoiceDialog_Description {
            get {
                return ResourceManager.GetString("editInvoiceDialog_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string editInvoiceDialog_Hours {
            get {
                return ResourceManager.GetString("editInvoiceDialog_Hours", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Price/Hour.
        /// </summary>
        public static string editInvoiceDialog_PricePerHour {
            get {
                return ResourceManager.GetString("editInvoiceDialog_PricePerHour", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string editInvoiceDialog_Total {
            get {
                return ResourceManager.GetString("editInvoiceDialog_Total", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Per Square Meter.
        /// </summary>
        public static string editInvoiceDialog_PerSquareMeter {
            get {
                return ResourceManager.GetString("editInvoiceDialog_PerSquareMeter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Area (m²).
        /// </summary>
        public static string editInvoiceDialog_Area {
            get {
                return ResourceManager.GetString("editInvoiceDialog_Area", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Price/m².
        /// </summary>
        public static string editInvoiceDialog_PricePerSquareMeter {
            get {
                return ResourceManager.GetString("editInvoiceDialog_PricePerSquareMeter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Fixed Price.
        /// </summary>
        public static string editInvoiceDialog_FixedPrice {
            get {
                return ResourceManager.GetString("editInvoiceDialog_FixedPrice", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Fixed Amount.
        /// </summary>
        public static string editInvoiceDialog_FixedAmount {
            get {
                return ResourceManager.GetString("editInvoiceDialog_FixedAmount", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Per Object.
        /// </summary>
        public static string editInvoiceDialog_PerObject {
            get {
                return ResourceManager.GetString("editInvoiceDialog_PerObject", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        public static string editInvoiceDialog_Objects {
            get {
                return ResourceManager.GetString("editInvoiceDialog_Objects", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Price/Object.
        /// </summary>
        public static string editInvoiceDialog_PricePerObject {
            get {
                return ResourceManager.GetString("editInvoiceDialog_PricePerObject", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string editInvoiceDialog_Save {
            get {
                return ResourceManager.GetString("editInvoiceDialog_Save", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string editInvoiceDialog_Cancel {
            get {
                return ResourceManager.GetString("editInvoiceDialog_Cancel", resourceCulture);
            }
        }
    }
}
